### PR TITLE
Fixed useNativeDriver warning

### PR DESCRIPTION
**Pull request by edi**
I've set it to false by default, since it wasn't defined at all beforehand. @EvanBacon if you want anything animation to specifically use it, let me know and I can update. 

Regards

### CODE REVIEW

**Comment by benlevy0** [comment]
@EvanBacon Can you merge this?

**Comment by s-rayed** [comment]
+1

**Comment by GoldfishPi** [comment]
+1

**Comment by lionc213** [comment]
I don't have this warning, why ? @edi ?

**Comment by edi** [comment]
> I don't have this warning, why ? @edi ?

Depends on the RN version you're on. But this is a thing since 2017, or maybe you've disabled your LogBox (yellowBox)

As for the others that need to implement this, you could just use `patch-package` until @EvanBacon finds some time to merge this in.

**Comment by EvanBacon** [comment]
Available in v2 https://snack.expo.dev/@bacon/rebellious-juice-box

**Pull request merged**
